language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq automake autoconf libtool make zlib1g-dev python
script:
 - autoreconf -f -i
 - ./configure --disable-silent-rules
 - make -j4
 - make -C tests check
